export const SET_BUSSEATINFO = 'SET_BUSSEATINFO';
export const SET_BUSSEATINFO_SUCCESS = 'SET_BUSSEATINFO_SUCCESS';
export const NUM_OF_PEOPLE = 'NUM_OF_PEOPLE';
export const SET_Seat_TYPE = 'SET_Seat_TYPE';
export const OPEN_BUSSEATSELECT = 'OPEN_BUSSEATSELECT';
//取得/order/getbusinfojson(旅客旅程資訊)
export const FETCH_PASSENGERPURPOSE = 'FETCH_PASSENGERPURPOSE';
export const PASSENGERPURPOSE = 'PASSENGERPURPOSE';

export const GO_NEXT = 'GO_NEXT';
export const CHANGE_SEAT = 'CHANGE_SEAT';
export const IS_CHANGE_SEAT_SUCCESS = 'IS_CHANGE_SEAT_SUCCESS';
//取得/order/getbusseatlistjson(取得座位)
export const FETCH_BUSSEATLISTPURPOSE = 'FETCH_BUSSEATLISTPURPOSE';
export const BUSSEATLISTPURPOSE = 'BUSSEATLISTPURPOSE';
export const FETCH_SEATLIST = 'FETCH_SEATLIST';
export const SELECTING = 'SELECTING';

// export const SET_POPULARINFO = 'SET_POPULARINFO';
// export const SET_POPULARINFO_SUCCESS = 'SET_POPULARINFO_SUCCESS';
// export const SET_FILTERITEMS = 'SET_FILTERITEMS';
// export const SET_TEMPFILTERITEMS = 'SET_TEMPFILTERITEMS';
// export const SET_SORTLISTBY = 'SET_SORTLISTBY';
// export const SET_SWITCHLISTBY = 'SET_SWITCHLISTBY';
// export const SET_TAGFILTERS_SHOW = 'SET_TAGFILTERS_SHOW';
// export const SET_TEMPTAGFILTERS_SHOW = 'SET_TEMPTAGFILTERS_SHOW';

// // search/GroupListInfoJson (取得熱銷與一般行程)

// export const SET_GROUPLISTINFO = 'SET_GROUPLISTINFO';
// export const SET_GROUPLISTINFO_SUCCESS = 'SET_GROUPLISTINFO_SUCCESS';
// export const SET_GROUPLISTINFOM = 'SET_GROUPLISTINFOM';
// export const SET_GROUPLISTINFOM_SUCCESS = 'SET_GROUPLISTINFOM_SUCCESS';
// export const SET_SINGLEGROUPLISTINFO = 'SET_SINGLEGROUPLISTINFO';
// export const SET_SINGLEGROUPLISTINFO_SUCCESS = 'SET_SINGLEGROUPLISTINFO_SUCCESS';
// export const SET_SINGLEGROUPLISTINFOM = 'SET_SINGLEGROUPLISTINFOM';
// export const SET_SINGLEGROUPLISTINFOM_SUCCESS = 'SET_SINGLEGROUPLISTINFOM_SUCCESS';
// export const SET_PAGESIZEM = 'SET_PAGESIZEM';
