export const SET_BUSSEATINFO = 'SET_BUSSEATINFO';
export const SET_BUSSEATINFO_SUCCESS = 'SET_BUSSEATINFO_SUCCESS';
export const SET_LIST_OPEN = 'SET_LIST_OPEN';
export const SET_PAGE = 'SET_PAGE';
