export const SET_PAGE = 'SET_PAGE';
export const SET_ISLOADING = 'SET_ISLOADING';

export const CALL_PRODUCT_GETALLPRODUCT = 'CALL_PRODUCT_GETALLPRODUCT';
export const SET_PRODUCT_GETALLPRODUCT = 'SET_PRODUCT_GETALLPRODUCT';
