const CarInfoData = [
    {
        CarTypeName: '52人車廂',
        CarTypeDescription: '客座車廂(52座位)',
        CarTypeCode: 'TranBike_BusinessCar',
        // CarTypeCode: Bus19 19座巴士, Bus19_S1 19座小可愛, Bus19_Sp 19座巴士(梅花座), Bus25 25座小可愛, Bus32 32人大巴
        // Bus34 34人大巴, Bus41 41人大巴, Bus41_Sp 41人大巴(梅花座), Bus43 43人大巴, Bus45 45人大巴
        // Sunrise_6Car 鳴日號(6節), Sunrise_BusinessCar 鳴日號(商務車廂), Sunrise_LivingCar 鳴日號(客廳車廂)
        // TranBike_6Car 兩鐵(6節), TranBike_BikeCar 兩鐵(人車車廂),TranBike_BusinessCar 兩鐵(一般車廂)
        CarNumber: null,
        //type:driv:駕駛,guid:導遊,aisl:走道,door:前門後門安全門,seat:可選,selected:你的座位,disabled:已選
        //row:向下幾行
        //col:向右幾欄
        Seats: [
            [
                {
                    idx: 1,
                    type: 'seat',
                    text: '1',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 3,
                    type: 'seat',
                    text: '3',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 0,
                    type: 'aisl',
                    text: '',
                    row: 13,
                    col: 1,
                },
                {
                    idx: 4,
                    type: 'seat',
                    text: '4',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 2,
                    type: 'seat',
                    text: '2',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 5,
                    type: 'disabled',
                    text: '5',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 7,
                    type: 'disabled',
                    text: '7',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 8,
                    type: 'seat',
                    text: '8',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 6,
                    type: 'seat',
                    text: '6',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 9,
                    type: 'seat',
                    text: '9',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 11,
                    type: 'seat',
                    text: '11',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 12,
                    type: 'disabled',
                    text: '12',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 10,
                    type: 'disabled',
                    text: '10',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 13,
                    type: 'seat',
                    text: '13',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 15,
                    type: 'seat',
                    text: '15',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 16,
                    type: 'seat',
                    text: '16',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 14,
                    type: 'seat',
                    text: '14',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 17,
                    type: 'seat',
                    text: '17',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 19,
                    type: 'seat',
                    text: '19',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 20,
                    type: 'seat',
                    text: '20',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 18,
                    type: 'seat',
                    text: '18',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 21,
                    type: 'seat',
                    text: '21',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 23,
                    type: 'seat',
                    text: '23',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 24,
                    type: 'seat',
                    text: '24',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 22,
                    type: 'seat',
                    text: '22',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 25,
                    type: 'seat',
                    text: '25',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 27,
                    type: 'seat',
                    text: '27',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 28,
                    type: 'seat',
                    text: '28',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 26,
                    type: 'seat',
                    text: '26',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 29,
                    type: 'seat',
                    text: '29',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 31,
                    type: 'seat',
                    text: '31',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 32,
                    type: 'seat',
                    text: '32',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 30,
                    type: 'seat',
                    text: '30',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 33,
                    type: 'seat',
                    text: '33',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 35,
                    type: 'seat',
                    text: '35',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 36,
                    type: 'seat',
                    text: '36',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 34,
                    type: 'seat',
                    text: '34',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 37,
                    type: 'seat',
                    text: '37',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 39,
                    type: 'seat',
                    text: '39',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 40,
                    type: 'seat',
                    text: '40',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 38,
                    type: 'seat',
                    text: '38',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 41,
                    type: 'seat',
                    text: '41',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 43,
                    type: 'seat',
                    text: '43',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 44,
                    type: 'seat',
                    text: '44',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 42,
                    type: 'seat',
                    text: '42',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 45,
                    type: 'seat',
                    text: '45',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 47,
                    type: 'seat',
                    text: '47',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 48,
                    type: 'seat',
                    text: '48',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 46,
                    type: 'seat',
                    text: '46',
                    row: 1,
                    col: 1,
                },
            ],
            [
                {
                    idx: 49,
                    type: 'seat',
                    text: '49',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 51,
                    type: 'seat',
                    text: '51',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 52,
                    type: 'seat',
                    text: '52',
                    row: 1,
                    col: 1,
                },
                {
                    idx: 50,
                    type: 'seat',
                    text: '50',
                    row: 1,
                    col: 1,
                },
            ],
        ],
    },
];

module.exports = CarInfoData;
