
export const CALL_PRODUCT_GETALLPRODUCT = 'CALL_PRODUCT_GETALLPRODUCT';
export const SET_PRODUCT_GETALLPRODUCT = 'SET_PRODUCT_GETALLPRODUCT';

export const SET_ISLOADING = 'SET_ISLOADING';

export const CALL_ORDER_LISTSHIPPING = 'CALL_ORDER_LISTSHIPPING';
export const SET_ORDER_LISTSHIPPING = 'SET_ORDER_LISTSHIPPING';